export { default as Beranda } from "./Beranda";
export { default as NoFound } from "./NoFound";
export { default as LamanStatis } from "./LamanStatis";
export { default as Berita } from "./Berita/Berita";
export { default as Artikel } from "./Artikel/Artikel";
export { default as BacaBerita } from "./Berita/BacaBerita";
export { default as BacaArtikel } from "./Artikel/BacaArtikel";
export { default as KategoriBerita } from "./Berita/KategoriBerita";
export { default as KategoriArtikel } from "./Artikel/KategoriArtikel";
